import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LabEngine} from './engine.js';
import {localApi as api} from './client.js';
import {GrokSession,applyAdvice} from '../core/grok.mjs';
import './style.css';

const stimuli=[['sugar','Sugar','Taste → feeding'],['loom','Looming shadow','Vision → escape'],['touch','Touch','Mechanosensory input'],['food','Food smell','Olfactory input']];
const nf=new Intl.NumberFormat('en-US');
function Plot({rows}){
  const colors=['#df4635','#319b9a','#b69758'],max=Math.max(10,...rows.flatMap(r=>r.values));
  return <div className="plot"><svg viewBox="0 0 440 115" role="img" aria-label="Measured neural firing rates in three output channels">
    {[0,1,2].map(i=><line key={i} x1="0" x2="440" y1={10+i*43} y2={10+i*43} stroke="#dfdfd7" strokeDasharray="3 5"/>)}
    {colors.map((c,k)=><polyline key={c} fill="none" stroke={c} strokeWidth="2" points={rows.map((r,i)=>`${i/Math.max(1,rows.length-1)*440},${100-r.values[k]/max*88}`).join(' ')}/>)}
  </svg><span className="scale">{max.toFixed(0)} Hz</span><div className="legend">{['Feeding','Escape','Turning'].map((t,i)=><span key={t}><i style={{background:colors[i]}}/>{t}</span>)}</div></div>;
}
function App(){
  const flyCanvas=useRef(),brainCanvas=useRef(),engine=useRef();
  const grok=useRef(new GrokSession()),keyInput=useRef(),runLock=useRef(false);
  const [advisor,setAdvisor]=useState('local'),[consent,setConsent]=useState(false),[limit,setLimit]=useState(5),[grokStatus,setGrokStatus]=useState(grok.current.status),[grokLog,setGrokLog]=useState([]);
  const [recording,setRecording]=useState('');
  const [state,setState]=useState({ready:false,phase:'Loading the connectome…',status:'loading',mode:'live',stimulus:'sugar',trace:[],spikes:0,t:0});
  const [report,setReport]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[seed,setSeed]=useState(100042),[policy,setPolicy]=useState('selective'),[current,setCurrent]=useState(null),[methods,setMethods]=useState(false),[preview,setPreview]=useState(null),[exported,setExported]=useState(false);
  useEffect(()=>{
    const e=new LabEngine(flyCanvas.current,brainCanvas.current,update=>setState(s=>({...s,...update})));
    engine.current=e;e.init().catch(err=>setError(err.message));
    api('status').then(s=>s.trained?api('results').then(setReport):null).catch(err=>setError(err.message));
    return()=>{e.dispose();grok.current.disconnect();};
  },[]);
  const stimulate=id=>{setCurrent(null);setError('');engine.current.stimulate(id);};
  async function train(){setBusy(true);setError('');try{setReport(await api('train',{method:'POST'}));}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function run(nextSeed=seed){
    if(runLock.current)return;runLock.current=true;setBusy(true);setError('');setCurrent(null);
    try{
      let result=await api(`trial?seed=${nextSeed}&mode=${policy}`);
      if(result.hints&&advisor==='grok'){
        const answer=await grok.current.hint(result);result=applyAdvice(result,answer);
        setGrokLog(rows=>[...rows,{seed:result.seed,branch:answer.branch===0?'left':'right',success:result.success,reason:answer.reason,usage:answer.usage,model:answer.model}]);
      }else if(!result.hints){result={...result,advisor:'none'};}
      setCurrent(result);setSeed(nextSeed);engine.current.playTrial(result);
    }catch(e){setError(e.message);}finally{runLock.current=false;setBusy(false);setGrokStatus(grok.current.status);}
  }
  function connectGrok(){setError('');try{grok.current.connect({key:keyInput.current.value,consent,limit:Number(limit)});keyInput.current.value='';setGrokStatus(grok.current.status);setAdvisor('grok');}catch(e){setError(e.message);}}
  function disconnectGrok(){grok.current.disconnect();if(keyInput.current)keyInput.current.value='';setConsent(false);setGrokStatus(grok.current.status);setAdvisor('local');}
  function exportResults(){const blob=new Blob([JSON.stringify({benchmarkAdvisor:'local full-state oracle',report,lastTrial:current,grokSession:{...grok.current.status,responses:grokLog}},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fly-assist-results.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExported(true);}
  const results=report?.results;
  const isTrial=state.mode==='trial';
  const liveAction=state.drive?.escape>0.25?'Escape response':state.drive?.proboscis>0.25?'Feeding response':state.drive?.walk>0.2?'Walking':'Neural activity';
  const action=isTrial?(state.phase||'Reading response'):liveAction;
  const reduction=results?Math.round((1-results.selective.hints/results.always.hints)*100):null;
  return <main>
    {new URLSearchParams(location.search).has('demo')&&<button disabled={!state.ready||busy} onClick={async()=>{setBusy(true);try{const {recordDemo}=await import('./record.js');const result=await api('trial?seed=100046&mode=selective');await recordDemo(engine.current,result,setRecording);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{recording||'Record local demo'}</button>}
    <header><a className="brand" href="#top" aria-label="Fly Assist home"><svg viewBox="0 0 32 32" aria-hidden="true"><ellipse cx="16" cy="20" rx="3" ry="8"/><circle cx="16" cy="9" r="4"/><path d="M13 17C-2-2 4-7 16 15C28-7 34-2 19 17M12 21l-6 5m14-5 6 5M12 15l-7 2m15-2 7 2" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>FLY <span>/</span> ASSIST</a><span className="local"><i/> Browser experiment <span className="edition">01 — EMBODIED</span></span></header>
    <section className="intro" id="top"><div><h1>A tiny brain.<br className="mobile-break"/> A second opinion.</h1><p className="intro-sub">A digital fly with a body. A neural readout that learns when to ask for help.</p></div><a className="text-link" href="#experiment">Try the experiment <span>↘</span></a></section>
    {error||state.error?<div role="alert" className="error">{error||state.error}</div>:null}
    <section className="specimen-grid" aria-label="Fly and connectome">
      <div className="specimen body-panel"><div className="panel-head"><span><b className="index">01</b> The body</span><span className="mono light">D. melanogaster</span></div>
        <canvas ref={flyCanvas} aria-label="Interactive three-dimensional fruit fly; drag to orbit and scroll to zoom"/>
        <div className="scene-top"><span className="live-tag"><i/>{isTrial?'FORAGING TRIAL':'LIVE RESPONSE'}</span><span className="scene-label">{isTrial?`SEED ${seed}`:'DRAG TO ORBIT'}</span></div>
        <div className="scene-caption"><span>{state.ready?action:state.phase}</span><button className="scene-button" disabled={!state.ready||state.status==='recording'} onClick={()=>engine.current.pause()}>{state.status==='paused'?'Resume':'Pause'}</button></div>
        {isTrial&&<div className="cue-label">{current?.marked?'DIRECTION CUE AVAILABLE':'NO DIRECTION CUE'}<span>{current?.hints?'Advisor requested':'Readout chooses directly'}</span></div>}
      </div>
      <div className="specimen brain-panel"><div className="panel-head"><span><b className="index">02</b> The brain</span><span className="mono light">FlyWire v783</span></div><canvas ref={brainCanvas} aria-label="Measured fruit-fly neuron positions with simulated spiking activity"/>
        <div className="brain-stats"><div><strong>{nf.format(state.neurons||138639)}</strong><span>neurons</span></div><div><strong>2.70M</strong><span>retained connections</span></div></div>
        <div className="scene-caption"><span className="mono">{(state.t||0).toFixed(0)} ms <span className="dim">simulated</span> · {nf.format(state.spikes||0)} spikes</span><span className="scene-label">{isTrial?'SEEDED RESPONSE':'LIF SIMULATION'}</span></div>
      </div>
    </section>
    <section className="stimulus-bar" aria-label="Sensory stimuli"><span className="bar-label">Give it a stimulus</span><div className="stimuli">{stimuli.map(([id,label,hint])=><button key={id} title={hint} disabled={!state.ready||busy} className={!isTrial&&state.stimulus===id?'selected':''} onClick={()=>stimulate(id)}><span>{label}</span><span className="arrow">↗</span></button>)}</div><span className="stimulus-note">Input → spikes → body</span></section>
    <section id="experiment" className="experiment"><div className="section-title"><div><p className="eyebrow">THE EXPERIMENT</p><h2>Can it learn when to ask?</h2></div><p>Two covered dishes. One contains food.<br/>A useful cue is present on roughly half the trials.</p></div>
      <div className="experiment-grid"><div className="controls-block"><div className="step-label">01 / LEARN</div><h3>Give help a small cost.</h3><p>The readout can turn left, turn right, or ask an advisor. Food earns +1; a wrong choice earns −1. A hint costs 0.35.</p><button className="primary" onClick={train} disabled={busy||!state.ready}>{busy?'Working…':'Train & compare'}<span>↗</span></button><p className="micro">{report?`Readout trained · ${nf.format(report.model.episodes)} reward-based updates`:'Train the output layer to unlock trials.'}</p></div>
      <div className="controls-block"><div className="step-label">02 / TRY</div><h3>Watch the choice become movement.</h3><div className="field-row"><label>Policy<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="selective">Learned readout</option><option value="none">No help</option><option value="always">Always ask</option></select></label><label>Trial seed<input aria-label="Trial seed" type="number" min="0" max="1000000000" value={seed} onChange={e=>setSeed(Number(e.target.value))}/></label></div><div className="button-row"><button onClick={()=>run()} disabled={!report||!state.ready||busy}>Run trial <span>→</span></button><button className="quiet" onClick={()=>run(seed+1)} disabled={!report||!state.ready||busy}>New trial</button></div><p className="micro">Advisor: {advisor==='grok'?'your Grok session':'local oracle (free)'} <span className="dot">·</span> {advisor==='grok'?`${grokStatus.attempts} / ${grokStatus.limit} requests attempted`:'No API requests'}</p></div>
      <div className="signals-block"><div className="step-label">03 / OBSERVE</div><div className="signal-title"><h3>Neural output</h3><span className="mono">{isTrial?'150 ms window':'LIVE'}</span></div><Plot rows={state.trace||[]}/><p className="micro">{isTrial?'Recorded spikes replayed at 10× slower speed.':'Rates measured from the running connectome.'}</p></div></div>
    </section>
    <section id="grok" className="grok-panel"><div><p className="eyebrow">BRING YOUR OWN ADVISOR</p><h2>Let it ask Grok.</h2><p>The readout chooses when to ask. Grok sees which dish contains food and returns a direction. Your key goes directly to xAI, stays in this tab’s memory and is cleared on disconnect or reload.</p><p className="micro">Model: Grok 4.20 non-reasoning · 120 output tokens maximum · no automatic retries.<br/>Create a restricted, low-budget key in your <a href="https://console.x.ai/" target="_blank" rel="noreferrer">xAI console ↗</a>. The request cap counts attempts, including failed requests; it is not a dollar budget. Train & compare always stays local.</p></div><div className="grok-form"><label>Advisor for individual trials<select aria-label="Advisor for individual trials" value={advisor} disabled={busy} onChange={e=>setAdvisor(e.target.value)}><option value="local">Local oracle — free</option><option value="grok">Grok — your API credits</option></select></label>{!grokStatus.enabled?<><div className="field-row"><label>xAI API key<input ref={keyInput} type="password" autoComplete="off" spellCheck="false" placeholder="Paste your key" aria-label="xAI API key"/></label><label>Request limit<input type="number" min="1" max="20" value={limit} onChange={e=>setLimit(e.target.value)}/></label></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I allow paid requests to xAI when I run a trial that asks for help.</label><button className="primary" onClick={connectGrok} disabled={!consent||busy}>Enable Grok for this tab ↗</button></>:<><p className="connected">Grok enabled · {grokStatus.attempts} / {grokStatus.limit} attempts</p><p className="micro">Your key is held in memory. Run an unmarked trial, such as seed 100046, to request a hint. Key validity is checked by xAI on the first request.</p><button onClick={disconnectGrok}>Disconnect & clear key</button></>}</div></section>
    {grokLog.length>0&&<section className="grok-log"><h3>Your Grok replies</h3>{grokLog.map((row,i)=><div key={i}><b>Seed {row.seed} → {row.branch} · {row.success?'food reached':'empty dish'}</b><p>{row.reason}</p><span className="micro">{row.usage.input} input / {row.usage.output} output tokens reported by xAI</span></div>)}</section>}
    <section className="results-section"><p className="eyebrow">LOCAL ADVISOR BENCHMARK</p><div className="results-heading"><h2>Same task. Three strategies.</h2><button className="quiet" onClick={exportResults} disabled={!report}>{exported?'Export again ↓':'Export results ↓'}</button></div><div className="table-scroll"><table><thead><tr><th>Policy</th><th>Food reached</th><th>Hints used</th><th>Mean reward</th></tr></thead><tbody>{[['none','No help','Chooses from the same movement readout'],['always','Always ask','Requests the correct arm every time'],['selective','Learned readout','Chooses whether a hint is worth its cost']].map(([key,name,desc])=><tr key={key} className={key==='selective'?'highlight':''}><td><strong>{name}</strong><span>{desc}</span></td><td>{results?`${results[key].success} / ${results[key].n}`:'—'}</td><td>{results?results[key].hints:'—'}</td><td>{results?results[key].reward.toFixed(3):'—'}</td></tr>)}</tbody></table></div>
      <div className="result-note"><p>{results?<><strong>{reduction}% fewer hints</strong> than always asking, on this test set.</>:'Train the readout to measure the difference.'}</p><span>256 seeded choices · 24 held-out neural recordings</span></div>
    </section>
    {current&&<section className="decision"><div><p className="eyebrow">LAST DECISION / {current.seed}</p><h3>{current.action==='ask'?'Ask, then move.':`Choose ${current.action}.`}</h3></div><p>{current.marked?'A direction cue was encoded into sensory neurons.':'No direction cue was provided.'} The readout chose <strong>{current.action}</strong> from the neural response. {current.hints?(current.advisor==='grok'?`Grok replied: ${current.advisorReason}`:'The local advisor supplied the food location.'):'No advisor was used.'}</p><div className="qvalues">{current.q.map((v,i)=><span key={i}>{['Left','Right','Ask'][i]} <b>{v.toFixed(2)}</b></span>)}</div></section>}
    <footer><span><i className="status-dot"/> {advisor==='grok'?'Grok selected':'Local advisor active'} <span className="sep">/</span> <a href="https://github.com/knapabuse2-cmd/fly-assist" target="_blank" rel="noreferrer">Source & methods ↗</a></span><button className="text-button" aria-expanded={methods} onClick={()=>setMethods(!methods)}>How this works {methods?'−':'+'}</button></footer>
    {methods&&<section className="methods"><div><h3>What is biological?</h3><p>The wiring and neuron locations come from FlyWire v783. A leaky integrate-and-fire simulation propagates activity through 138,639 neurons and 2,700,513 retained connections. Edges with fewer than five synaptic contacts were removed in the upstream dataset.</p><p>The articulated body, motor mapping and virtual environment are engineered. The body uses a procedural model with a tripod gait; it is not a physics reconstruction of every muscle.</p></div><div><h3>What learns?</h3><p>A linear output layer learns three action values from 58 downstream firing-rate features. The connectome stays fixed. In this toy task, left, right and missing cues are deliberately encoded as sugar, touch and looming stimulation. This is an artificial interface, not natural visual reasoning by a fly.</p><p>Training uses 36 seeded response windows. Testing uses 24 independently seeded windows, reused across 256 new trial seeds. This tests a simple decision rule; it does not demonstrate general intelligence or biological learning.</p></div><div><h3>Where is Grok?</h3><p>The comparison table uses a local advisor with the full food state. Individual trials can use your own Grok key instead. Grok receives the same full state and returns a direction; its actual choice determines the outcome. Live replies and token usage appear in a separate session log. A failed request stops the trial without substituting a local hint.</p><button className="quiet" onClick={async()=>{try{setPreview(await api('grok/request-preview'));}catch(e){setError(e.message);}}}>Preview Grok request</button>{preview&&<pre>{JSON.stringify(preview,null,2)}</pre>}<p><a href="https://github.com/RaphaelSR/fly-brain-bench" target="_blank" rel="noreferrer">Fly Brain Bench · Raphael Rocha ↗</a><br/><a href={import.meta.env.BASE_URL+"data/ATTRIBUTION.md"} target="_blank">FlyWire data · CC BY 4.0 ↗</a><br/><a href={import.meta.env.BASE_URL+"vendor/LICENSE"} target="_blank">Upstream code · MIT ↗</a></p>{results&&<p>Control: assigning unrelated neural recordings to trials reduces success to {results.shuffled.success}/{results.shuffled.n}, with {results.shuffled.hints} hints.</p>}</div></section>}
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
